name: Build on Linux
on: [push, pull_request]

jobs:
  linux-ubuntu:
    runs-on: ubuntu-latest
    container: ${{ matrix.image }}
    strategy:
      matrix:
        include:
          - image: ubuntu:22.04
            dependencies: >
              build-essential cmake pkg-config desktop-file-utils libgl1-mesa-dev libglu1-mesa-dev
              qmake6 qttools5-dev qtbase5-dev libqt5x11extras5-dev libavformat-dev libavcodec-dev libavutil-dev
              libswscale-dev libasound2-dev libpulse-dev libjack-dev libx11-dev libxext-dev libxfixes-dev libxi-dev
              libxinerama-dev libv4l-dev
          - image: ubuntu:20.04
            dependencies: >
              build-essential cmake pkg-config desktop-file-utils libgl1-mesa-dev libglu1-mesa-dev
              qt5-qmake qttools5-dev qtbase5-dev libqt5x11extras5-dev libavformat-dev libavcodec-dev libavutil-dev
              libswscale-dev libasound2-dev libpulse-dev libjack-dev libx11-dev libxext-dev libxfixes-dev libxi-dev
              libxinerama-dev libv4l-dev
          - image: ubuntu:18.04
            dependencies: >
              build-essential pkg-config qt4-qmake libqt4-dev libavformat-dev
              libavcodec-dev libavutil-dev libswscale-dev libasound2-dev libpulse-dev libjack-jackd2-dev
              libgl1-mesa-dev libglu1-mesa-dev libx11-dev libxfixes-dev libxext-dev libxi-dev g++
          - image: ubuntu:16.04
            dependencies: >
              build-essential pkg-config qt4-qmake libqt4-dev libavformat-dev
              libavcodec-dev libavutil-dev libswscale-dev libasound2-dev libpulse-dev libjack-jackd2-dev
              libgl1-mesa-dev libglu1-mesa-dev libx11-dev libxfixes-dev libxext-dev libxi-dev g++
          - image: ubuntu:14.04
            dependencies: >
              build-essential pkg-config qt4-qmake libqt4-dev libavformat-dev
              libavcodec-dev libavutil-dev libswscale-dev libasound2-dev libpulse-dev libjack-jackd2-dev
              libgl1-mesa-dev libglu1-mesa-dev libx11-dev libxfixes-dev libxext-dev libxi-dev g++

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: apt-get update && apt-get -y install ${{ matrix.dependencies }}

      - name: Build
        run: ./simple-build-and-install
